### PR TITLE
Don't always include e.g. the history package

### PR DESCRIPTION
**Pull request by taion**
Fixes https://github.com/npm/npm/issues/9642

### CODE REVIEW

**Comment by taion** [comment]
Oops, hold on.

**Comment by taion** [comment]
Fixed. I flipped the conditional on accident. I improved the test to also catch that.

For reasons unclear to me, cleanup fails with `rimraf.sync`, so I switched to using async `rimraf` there.

**Comment by thomblake** [comment]
@othiym23 This would be super-helpful

**Comment by othiym23** [comment]
It's got a test, the problem is real, and I'll try to get this merged and released shortly! Thanks for the nudge, @thomblake!

**Comment by taion** [comment]
Thanks!

**Comment by othiym23** [comment]
Included in `fstream-npm@1.0.6`, which will be landed in npm shortly. Thank you!

**Comment by othiym23** [comment]
Landed in npm as 66abc606de8409991c557fbb6fda7eeb639a5fdf in `release-3.4.0`, and 3308daf49726322b9f39679ceb3b0823d559ce13 in `npm-2.14.10`.

**Comment by thomblake** [comment]
Awesome!

**Comment by timaschew** [comment]
still broken with npm 2.14.10

```
$ npm --version
2.14.10

$ cat package.json
{
  "name": "test1",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "redux-router": "^1.0.0-beta3"
  }
}

$ npm i
npm WARN package.json test1@1.0.0 No description
npm WARN package.json test1@1.0.0 No repository field.
npm WARN package.json test1@1.0.0 No README data
npm WARN package.json test1@1.0.0 No license field.
redux-router@1.0.0-beta4 node_modules/redux-router
└── deep-equal@1.0.1

$ npm ls
test1@1.0.0 /Users/awilhelm/dev/test1
└─┬ redux-router@1.0.0-beta4
  ├── deep-equal@1.0.1
  └── history@1.9.0 extraneous

npm ERR! extraneous: history@1.9.0 /Users/awilhelm/dev/test1/node_modules/redux-router/node_modules/history

$ npm shrinkwrap
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/share/npm/bin/npm" "shrinkwrap"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.10

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: history@1.9.0 /Users/awilhelm/dev/test1/node_modules/redux-router/node_modules/history
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/awilhelm/dev/test1/npm-debug.log
```

**Comment by taion** [comment]
This was a fix for _packagers_, not for users.

**Comment by timaschew** [comment]
So the module needs to be published again? 
Which one, __history__ itself or all modules which rely on __history__?

**Comment by taion** [comment]
Every module that depends on history, yes. The issue was that the packed tarballs included history - that directory doesn't get expunged from the tarballs already released to npm just because we've patched fstream-npm.

**Comment by zhiyelee** [comment]
Awesome thanks!

**Comment by taion** [comment]
@othiym23 It looks like the equivalent file is vendored for npm3 per https://github.com/npm/npm/blob/v3.5.2/lib/utils/tar.js#L64, so this bug is actually not fixed for npm3 users. How can we go about getting this resolved?

**Comment by lukekarrys** [comment]
@taion I created a PR to fix it for npm@3 but never found the time to go back and add tests to the PR https://github.com/npm/npm/pull/10445 From the comments over there, it sounds like once tests get added it can be merged.

**Comment by taion** [comment]
@lukekarrys Thanks!

**Pull request merged**
